services:

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: influencer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      - db
      - redis
