import logging
import time
import uuid

logger = logging.getLogger(__name__)


class RequestLoggingMiddleware:
    """
    Adds a correlation/request ID to every HTTP request.

    The ID is:
    - taken from X-Request-ID when supplied by a trusted caller, or
    - generated by the application otherwise.

    It is returned to the client through the X-Request-ID response header.
    """

    HEADER_NAME = "HTTP_X_REQUEST_ID"
    RESPONSE_HEADER_NAME = "X-Request-ID"

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        request_id = request.META.get(self.HEADER_NAME)

        if not request_id:
            request_id = str(uuid.uuid4())

        request.request_id = request_id

        start_time = time.perf_counter()

        try:
            response = self.get_response(request)
        except Exception:
            duration_ms = round(
                (time.perf_counter() - start_time) * 1000,
                2,
            )

            logger.exception(
                "API request failed | "
                "request_id=%s method=%s path=%s duration_ms=%s",
                request_id,
                request.method,
                request.path,
                duration_ms,
            )

            raise

        duration_ms = round(
            (time.perf_counter() - start_time) * 1000,
            2,
        )

        response[self.RESPONSE_HEADER_NAME] = request_id

        logger.info(
            "API request | "
            "request_id=%s method=%s path=%s status=%s duration_ms=%s",
            request_id,
            request.method,
            request.path,
            response.status_code,
            duration_ms,
        )

        return response
