name: Django CI/CD

on:
  push:
    branches:
      - Dev
      - main

  pull_request:
    branches:
      - Dev
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black
        run: black --check .

      - name: isort
        run: isort --check-only .

      - name: Ruff
        run: ruff check .

      - name: Run Tests
        run: pytest


  deploy:

    needs: test

    if: github.event_name == 'push' && (github.ref == 'refs/heads/Dev' || github.ref == 'refs/heads/main')

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd ~/Influencer_analytics

            echo "Pulling latest code..."
            git checkout Dev
            git pull origin Dev

            echo "Building production Docker images..."
            docker compose -f docker-compose.prod.yml --env-file .env.prod build

            echo "Running database migrations..."
            docker compose -f docker-compose.prod.yml --env-file .env.prod run --rm web python manage.py migrate

            echo "Restarting production services..."
            docker compose -f docker-compose.prod.yml --env-file .env.prod up -d

            echo "Checking service status..."
            docker compose -f docker-compose.prod.yml --env-file .env.prod ps

            echo "Deployment completed successfully."